"""adiciona campos ausentes: administrador, cpf, auth_credenciais

Revision ID: 061dde95300c
Revises: 4f67b9f9475c
Create Date: 2025-06-18 21:33:34.903028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '061dde95300c'
down_revision = '4f67b9f9475c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.String(length=14), nullable=True))
        batch_op.add_column(sa.Column('senha_autoprf', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('token_autoprf', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('senha_siscom', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('senha_sei', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('token_sei', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint('uq_user_cpf', ['cpf'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_cpf', type_='unique')
        batch_op.drop_column('token_sei')
        batch_op.drop_column('senha_sei')
        batch_op.drop_column('senha_siscom')
        batch_op.drop_column('token_autoprf')
        batch_op.drop_column('senha_autoprf')
        batch_op.drop_column('cpf')

    # ### end Alembic commands ###
