"""Adiciona campo administrador ao usuário

Revision ID: 162175ccc6ea
Revises: 4f67b9f9475c
Create Date: 2025-06-19 09:19:29.177080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '162175ccc6ea'
down_revision = '4f67b9f9475c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('administrador', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint('uq_user_cpf', ['cpf'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_cpf', type_='unique')
        batch_op.drop_column('administrador')

    # ### end Alembic commands ###
