"""drop senha columns

Revision ID: 7d86a2d03204
Revises: a07535fc0e0d
Create Date: 2025-07-03 23:36:56.917453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d86a2d03204'
down_revision = 'a07535fc0e0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('senha_autoprf')
        batch_op.drop_column('senha_siscom')
        batch_op.drop_column('senha_sei')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha_sei', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('senha_siscom', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('senha_autoprf', sa.VARCHAR(length=120), nullable=True))

    # ### end Alembic commands ###
