"""initial

Revision ID: 9052a51204f5
Revises: 
Create Date: 2025-12-11 14:58:25.005408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9052a51204f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('administrador', sa.Boolean(), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('autoprf_session', sa.Text(), nullable=True),
    sa.Column('sei_session', sa.Text(), nullable=True),
    sa.Column('sei_home_html', sa.Text(), nullable=True),
    sa.Column('usuario_sei', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
