"""add autoprf_session

Revision ID: dc56a59e0e34
Revises: 162175ccc6ea
Create Date: 2025-06-19 13:54:56.963735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc56a59e0e34'
down_revision = '162175ccc6ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('autoprf_session', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('autoprf_session')

    # ### end Alembic commands ###
